[build]
buildCommand = "npm install --include=dev && ./node_modules/.bin/tsc -p tsconfig.build.json --noEmitOnError false && ls -la dist"

[deploy]
startCommand = "npx prisma migrate deploy && node dist/main"